# Generated by Django 2.1.4 on 2018-12-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='deleted',
        ),
    ]
