# Generated by Django 2.1.4 on 2018-12-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
